package com.mobilemessenger.backend.storage;

/**
 * Generic filesystem-backed storage for uploaded binary files.
 *
 * Files are grouped under a {@code category} (e.g. {@code "avatars"}) so the
 * same abstraction can later serve other upload kinds - chat images, videos,
 * audio - without changing this interface. Storage keys ("stored file
 * names") are always generated by the implementation, never derived from
 * client-supplied file names.
 *
 * <p>Every implementation encrypts file content at rest (AES-256-GCM - see
 * {@link com.mobilemessenger.backend.security.encryption.EncryptionService}):
 * callers always deal in plaintext bytes and plaintext lengths, and never
 * see the on-disk encrypted representation. {@link #loadRange} exists
 * specifically so a caller serving a large file (e.g. video, via HTTP range
 * requests) can decrypt only the portion actually requested, without
 * reading or decrypting the whole file - see {@link
 * LocalFileStorageService} for how that's implemented.
 */
public interface FileStorageService {

    /**
     * Stores {@code content} under {@code category} and returns the
     * generated storage key (a safe, server-chosen file name).
     */
    String store(String category, byte[] content, String fileExtension);

    /** Reads back a previously stored file's full plaintext bytes. Only suitable for small files (avatars, thumbnails). */
    byte[] load(String category, String storedFileName);

    /**
     * Reads back {@code [startInclusive, endInclusive]} of a previously
     * stored file's plaintext bytes, decrypting only what overlaps that
     * range. The range is clamped to the file's actual bounds.
     */
    byte[] loadRange(String category, String storedFileName, long startInclusive, long endInclusive);

    boolean exists(String category, String storedFileName);

    void delete(String category, String storedFileName);

    /** The stored file's plaintext size in bytes (not its larger on-disk encrypted size). */
    long size(String category, String storedFileName);
}
