package com.mobilemessenger.backend.storage;

/**
 * Generic filesystem-backed storage for uploaded binary files.
 *
 * Files are grouped under a {@code category} (e.g. {@code "avatars"}) so the
 * same abstraction can later serve other upload kinds - chat images, videos,
 * audio - without changing this interface. Storage keys ("stored file
 * names") are always generated by the implementation, never derived from
 * client-supplied file names.
 */
public interface FileStorageService {

    /**
     * Stores {@code content} under {@code category} and returns the
     * generated storage key (a safe, server-chosen file name).
     */
    String store(String category, byte[] content, String fileExtension);

    /** Reads back a previously stored file's bytes. */
    byte[] load(String category, String storedFileName);

    boolean exists(String category, String storedFileName);

    void delete(String category, String storedFileName);
}
