package com.mobilemessenger.backend.storage;

import org.springframework.core.io.Resource;

/**
 * Generic filesystem-backed storage for uploaded binary files.
 *
 * Files are grouped under a {@code category} (e.g. {@code "avatars"}) so the
 * same abstraction can later serve other upload kinds - chat images, videos,
 * audio - without changing this interface. Storage keys ("stored file
 * names") are always generated by the implementation, never derived from
 * client-supplied file names.
 */
public interface FileStorageService {

    /**
     * Stores {@code content} under {@code category} and returns the
     * generated storage key (a safe, server-chosen file name).
     */
    String store(String category, byte[] content, String fileExtension);

    /** Reads back a previously stored file's bytes. */
    byte[] load(String category, String storedFileName);

    boolean exists(String category, String storedFileName);

    void delete(String category, String storedFileName);

    /**
     * A streamable handle on a previously stored file, for callers that
     * shouldn't load the whole thing into memory at once (e.g. serving a
     * large video with HTTP range requests). {@link #size} is exposed
     * separately since a caller typically needs the total length up front
     * (e.g. for a {@code Content-Length} header or to compute a byte range)
     * without necessarily opening the resource yet.
     */
    Resource loadAsResource(String category, String storedFileName);

    /** The stored file's size in bytes. */
    long size(String category, String storedFileName);
}
