const { launch, snapshot, typeInto, enableSemantics, APP } = require('./lib');
const { createUser, befriend, call, PASSWORD, unique } = require('./api');
(async () => {
  const alice = await createUser(unique('ma'));
  const bob = await createUser(unique('mb'));
  const carol = await createUser(unique('mc'));
  const chatId = await befriend(alice, bob);
  await befriend(alice, carol);
  await call('POST', `/api/chats/${chatId}/messages`, bob.token, { content: 'phone hello' });
  const browser = await launch();
  const ctx = await browser.newContext({ viewport: { width: 400, height: 820 } });
  const p = await ctx.newPage();
  const errors = [];
  p.on('console', m => { if (m.type() === 'error') errors.push(m.text().slice(0, 200)); });
  p.on('pageerror', e => errors.push('PAGEERROR ' + String(e).slice(0, 200)));
  await p.goto(APP);
  await p.waitForSelector('flt-glass-pane, flutter-view');
  await enableSemantics(p);
  await p.waitForTimeout(800);
  await typeInto(p, p.getByRole('textbox', { name: 'Username or email' }), alice.username);
  await typeInto(p, p.getByRole('textbox', { name: 'Password' }), PASSWORD);
  await p.getByRole('button', { name: 'Log in', exact: true }).click();
  await p.getByText(`Welcome, ${alice.username}`).waitFor({ timeout: 15000 });
  console.log('phone layout: home screen OK (no desktop shell):', (await p.getByRole('tab').count()) === 0);
  await p.screenshot({ path: 'mobile_home.png' });
  await p.getByRole('button', { name: 'Chats' }).click();
  await p.getByRole('button', { name: /New group/ }).waitFor();
  await p.screenshot({ path: 'mobile_chats.png' });
  await p.getByRole('button', { name: new RegExp('^' + bob.username) }).first().click();
  await p.getByRole('textbox', { name: 'Message' }).waitFor();
  await p.getByText('phone hello').first().waitFor();
  await p.screenshot({ path: 'mobile_chat.png' });
  // search + info on the phone
  await p.getByRole('button', { name: 'Search in chat' }).click();
  await typeInto(p, p.getByRole('textbox', { name: 'Search in this chat' }), 'phone');
  await p.keyboard.press('Enter');
  await p.getByText('1 of 1').waitFor({ timeout: 8000 });
  await p.screenshot({ path: 'mobile_search.png' });
  console.log('phone: chat + search OK');
  console.log('console errors:', errors);
  await browser.close();
})().catch(e => { console.error('FAIL', e.message.split('\n')[0]); process.exit(1); });
