package com.mobilemessenger.backend.auth.session;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.UUID;

/**
 * One signed-in device or browser. The id is generated by the application
 * (not the database) because it must be known before the JWT that carries it
 * is signed.
 */
@Entity
@Table(name = "auth_sessions")
public class AuthSession {

    @Id
    private UUID id;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Column(name = "device_label", nullable = false, length = 100)
    private String deviceLabel;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "last_seen_at", nullable = false)
    private Instant lastSeenAt;

    @Column(name = "revoked_at")
    private Instant revokedAt;

    protected AuthSession() {
        // for JPA
    }

    public AuthSession(UUID userId, String deviceLabel) {
        this.id = UUID.randomUUID();
        this.userId = userId;
        this.deviceLabel = deviceLabel;
        this.createdAt = Instant.now();
        this.lastSeenAt = this.createdAt;
    }

    public UUID getId() { return id; }
    public UUID getUserId() { return userId; }
    public String getDeviceLabel() { return deviceLabel; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getLastSeenAt() { return lastSeenAt; }
    public Instant getRevokedAt() { return revokedAt; }

    public boolean isRevoked() {
        return revokedAt != null;
    }

    public void revoke() {
        if (revokedAt == null) {
            revokedAt = Instant.now();
        }
    }

    public void touch(Instant at) {
        this.lastSeenAt = at;
    }
}
